// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250425174948_SECONDITER")]
    partial class SECONDITER
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Grupa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Informatyka"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Matematyka"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Fizyka"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Chemia"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Biologia"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Ekonomia"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Psychologia"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Filozofia"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Historia"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Prawo"
                        });
                });

            modelBuilder.Entity("DAL.Models.Historia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IDGrupy")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("History");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ActionType = "edit",
                            Date = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 1,
                            Imie = "Jan",
                            Nazwisko = "Kowalski"
                        },
                        new
                        {
                            ID = 2,
                            ActionType = "delete",
                            Date = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 1,
                            Imie = "Anna",
                            Nazwisko = "Nowak"
                        },
                        new
                        {
                            ID = 3,
                            ActionType = "edit",
                            Date = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 2,
                            Imie = "Piotr",
                            Nazwisko = "Wiśniewski"
                        },
                        new
                        {
                            ID = 4,
                            ActionType = "edit",
                            Date = new DateTime(2023, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 2,
                            Imie = "Katarzyna",
                            Nazwisko = "Wójcik"
                        },
                        new
                        {
                            ID = 5,
                            ActionType = "delete",
                            Date = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 3,
                            Imie = "Michał",
                            Nazwisko = "Kowalczyk"
                        },
                        new
                        {
                            ID = 6,
                            ActionType = "edit",
                            Date = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 3,
                            Imie = "Agnieszka",
                            Nazwisko = "Kamińska"
                        },
                        new
                        {
                            ID = 7,
                            ActionType = "delete",
                            Date = new DateTime(2023, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 4,
                            Imie = "Tomasz",
                            Nazwisko = "Lewandowski"
                        },
                        new
                        {
                            ID = 8,
                            ActionType = "edit",
                            Date = new DateTime(2023, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 4,
                            Imie = "Magdalena",
                            Nazwisko = "Dąbrowska"
                        },
                        new
                        {
                            ID = 9,
                            ActionType = "edit",
                            Date = new DateTime(2023, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 5,
                            Imie = "Marcin",
                            Nazwisko = "Zieliński"
                        },
                        new
                        {
                            ID = 10,
                            ActionType = "delete",
                            Date = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 5,
                            Imie = "Monika",
                            Nazwisko = "Szymańska"
                        },
                        new
                        {
                            ID = 11,
                            ActionType = "edit",
                            Date = new DateTime(2023, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 6,
                            Imie = "Adam",
                            Nazwisko = "Woźniak"
                        },
                        new
                        {
                            ID = 12,
                            ActionType = "edit",
                            Date = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 6,
                            Imie = "Barbara",
                            Nazwisko = "Kozłowska"
                        },
                        new
                        {
                            ID = 13,
                            ActionType = "delete",
                            Date = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 7,
                            Imie = "Grzegorz",
                            Nazwisko = "Jankowski"
                        },
                        new
                        {
                            ID = 14,
                            ActionType = "edit",
                            Date = new DateTime(2023, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 7,
                            Imie = "Ewa",
                            Nazwisko = "Mazur"
                        },
                        new
                        {
                            ID = 15,
                            ActionType = "edit",
                            Date = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDGrupy = 8,
                            Imie = "Dariusz",
                            Nazwisko = "Kwiatkowski"
                        });
                });

            modelBuilder.Entity("DAL.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("IDGrupy")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDGrupy");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IDGrupy = 1,
                            Imie = "Jan",
                            Nazwisko = "Kowalski"
                        },
                        new
                        {
                            ID = 2,
                            IDGrupy = 1,
                            Imie = "Anna",
                            Nazwisko = "Nowak"
                        },
                        new
                        {
                            ID = 3,
                            IDGrupy = 2,
                            Imie = "Piotr",
                            Nazwisko = "Wiśniewski"
                        },
                        new
                        {
                            ID = 4,
                            IDGrupy = 2,
                            Imie = "Katarzyna",
                            Nazwisko = "Wójcik"
                        },
                        new
                        {
                            ID = 5,
                            IDGrupy = 3,
                            Imie = "Michał",
                            Nazwisko = "Kowalczyk"
                        },
                        new
                        {
                            ID = 6,
                            IDGrupy = 3,
                            Imie = "Agnieszka",
                            Nazwisko = "Kamińska"
                        },
                        new
                        {
                            ID = 7,
                            IDGrupy = 4,
                            Imie = "Tomasz",
                            Nazwisko = "Lewandowski"
                        },
                        new
                        {
                            ID = 8,
                            IDGrupy = 4,
                            Imie = "Magdalena",
                            Nazwisko = "Dąbrowska"
                        },
                        new
                        {
                            ID = 9,
                            IDGrupy = 5,
                            Imie = "Marcin",
                            Nazwisko = "Zieliński"
                        },
                        new
                        {
                            ID = 10,
                            IDGrupy = 5,
                            Imie = "Monika",
                            Nazwisko = "Szymańska"
                        },
                        new
                        {
                            ID = 11,
                            IDGrupy = 6,
                            Imie = "Adam",
                            Nazwisko = "Woźniak"
                        },
                        new
                        {
                            ID = 12,
                            IDGrupy = 6,
                            Imie = "Barbara",
                            Nazwisko = "Kozłowska"
                        },
                        new
                        {
                            ID = 13,
                            IDGrupy = 7,
                            Imie = "Grzegorz",
                            Nazwisko = "Jankowski"
                        },
                        new
                        {
                            ID = 14,
                            IDGrupy = 7,
                            Imie = "Ewa",
                            Nazwisko = "Mazur"
                        },
                        new
                        {
                            ID = 15,
                            IDGrupy = 8,
                            Imie = "Dariusz",
                            Nazwisko = "Kwiatkowski"
                        },
                        new
                        {
                            ID = 16,
                            IDGrupy = 8,
                            Imie = "Joanna",
                            Nazwisko = "Grabowska"
                        },
                        new
                        {
                            ID = 17,
                            IDGrupy = 9,
                            Imie = "Robert",
                            Nazwisko = "Kaczmarek"
                        },
                        new
                        {
                            ID = 18,
                            IDGrupy = 9,
                            Imie = "Aleksandra",
                            Nazwisko = "Pawlak"
                        },
                        new
                        {
                            ID = 19,
                            IDGrupy = 10,
                            Imie = "Paweł",
                            Nazwisko = "Michalak"
                        },
                        new
                        {
                            ID = 20,
                            IDGrupy = 10,
                            Imie = "Natalia",
                            Nazwisko = "Nowicka"
                        },
                        new
                        {
                            ID = 21,
                            Imie = "Krzysztof",
                            Nazwisko = "Adamczyk"
                        },
                        new
                        {
                            ID = 22,
                            Imie = "Weronika",
                            Nazwisko = "Dudek"
                        },
                        new
                        {
                            ID = 23,
                            Imie = "Łukasz",
                            Nazwisko = "Stępień"
                        },
                        new
                        {
                            ID = 24,
                            Imie = "Karolina",
                            Nazwisko = "Wróbel"
                        });
                });

            modelBuilder.Entity("DAL.Models.Student", b =>
                {
                    b.HasOne("DAL.Models.Grupa", "Grupa")
                        .WithMany("Students")
                        .HasForeignKey("IDGrupy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Grupa");
                });

            modelBuilder.Entity("DAL.Models.Grupa", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
